name: Deploy Java App to EC2 Tomcat

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean package

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.war

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: target

      - name: Deploy WAR to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$HOSTNAME" >> ~/.ssh/known_hosts

          # Copy WAR to EC2
          scp -i ~/.ssh/id_rsa target/*.war ec2-user@$HOSTNAME:/home/ec2-user/

          # Move WAR to Tomcat webapps
          ssh -i ~/.ssh/id_rsa ec2-user@$HOSTNAME 'sudo mv /home/ec2-user/*.war /opt/tomcat9/webapps/'

