name: Node.js CI & Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests (if any)
      run: |
        if npm run | grep -q 'test'; then
          npm test
        else
          echo "No test script defined"
        fi

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/your-app-folder || mkdir ~/your-app-folder && cd ~/your-app-folder
          git clone https://github.com/Hafiz-mn/java_project.git repo || cd repo && git pull
          cd repo
          npm install
          pm2 restart app.js || pm2 start app.js
