name: CI/CD with Nexus and EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up .npmrc for Nexus
        run: |
          echo "//${NPM_REGISTRY_URL#http://}:_auth=$(echo -n '${NPM_USERNAME}:${NPM_PASSWORD}' | base64)" > ~/.npmrc
          echo "registry=${NPM_REGISTRY_URL}" >> ~/.npmrc
        env:
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_PASSWORD: ${{ secrets.NPM_PASSWORD }}
          NPM_REGISTRY_URL: ${{ secrets.NPM_REGISTRY_URL }}

      - name: Install dependencies
        run: npm install

      # Optional: Publish to Nexus if needed
      - name: Publish package to Nexus
        run: npm publish

      - name: Deploy to EC2 via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$HOSTNAME" >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/id_rsa ec2-user@$HOSTNAME << 'EOF'
            if [ ! -d "app" ]; then
              git clone https://github.com/Hafiz-mn/java_project.git app
            else
              cd app && git pull
            fi
            cd app
            npm install
            pm2 restart app.js || pm2 start app.js
          EOF

